### ISSUE TITLE
Can't communicate with programmer!

### ISSUE THREAD

**Issue by gmonterroso** [arduino-libraries/UnoWiFi-FirmwareUpdater-Plugin#2]
I've tried to update the firmware using Ubuntu 14.04 and Raspbian and got this messages on both:

Ubuntu 14.04
java.lang.Exception: Can't communicate with programmer!
	at cc.arduino.plugins.unowifi.flashers.cli.CLIFlasher.testConnection(CLIFlasher.java:100)
	at cc.arduino.plugins.unowifi.UpdaterImpl$2.run(UpdaterImpl.java:112)

Raspbian
Picked up JAVA_TOOL_OPTIONS:
Xlib:  extension "RANDR" missing on display ":1.0".
java.lang.Exception: Programmer not responding
        at cc.arduino.plugins.wifi101.flashers.java.FlasherSerialClient.hello(FlasherSerialClient.java:105)
        at cc.arduino.plugins.wifi101.flashers.java.JavaFlasher.testConnection(JavaFlasher.java:51)
        at cc.arduino.plugins.wifi101.UpdaterImpl$2.run(UpdaterImpl.java:110)
java.lang.Exception: Can't communicate with programmer!
        at cc.arduino.plugins.unowifi.flashers.cli.CLIFlasher.testConnection(CLIFlasher.java:100)
        at cc.arduino.plugins.unowifi.UpdaterImpl$2.run(UpdaterImpl.java:112)

Can you help, please?

Thank you

**Comment by sergiotomasello** [comment]
@gmonterroso did you upload first `EspRecovery.ino` sketch and put the board in dfu mode?
Take a look [here](http://www.arduino.org/learning/tutorials/advanced-guides/arduino-uno-wifi-firmware-updater) and let me know.
Regards

**Comment by gmonterroso** [comment]
I updated the firmware using Windows and it worked.
